public class SalesForceDeveloper {
    public void myFirstCode(){
        String city = 'Kars';
        String movie = 'Tosun Pasa ';
        String seasons = 'Spring ';
        System.debug(city);
        System.debug(movie);
        System.debug(seasons); 


    }
    public void myFavorites(){
        String myCity = 'New York';
        Integer myNumber = 7;
        System.debug('I live in ' + mycity + ' for  '  + mynumber + ' years. ');
    }

}
